# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

#

export JAVA_HOME="/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.75.x86_64"
export JRE_HOME=/usr/java/default/jre
export ANT_HOME=/usr/share/ant
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib:/usr/share/ant/lib/ant-launcher.jar

export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin:$ANT_HOME/bin


#Hadoop
export HADOOP_HOME="/usr/local/hadoop-2.4.1"
export HADOOP_INSTALL=$HADOOP_HOME
export HADOOP_MAPRED_HOME=$HADOOP_HOME
export HADOOP_COMMON_HOME=$HADOOP_HOME
export HADOOP_HDFS_HOME=$HADOOP_HOME
export YARN_HOME=$HADOOP_HOME
export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin




#Hive
export HADOOP_PREFIX=/opt/hadoop
export HIVE_HOME=/opt/hive
export PATH=$HIVE_HOME/bin:$PATH


#Spark
export PATH=/opt/spark/bin:$PATH


